export const items = {
  woodfarm: {
    name: "Wood Farm",
    category: "Farms",
    price: { wood: 30, stone: 10 },
    description: "+5 wood per second",
    rate: { wood: 5 },
    model: "woodfarm",
    image: "img/wood.png",
  },
  sawmill: {
    name: "Sawmill",
    category: "Farms",
    price: { wood: 80, stone: 40 },
    description: "+15 wood per second (requires power)",
    rate: { wood: 15 },
    model: "sawmill",
    image: "img/wood.png",
  },
  stonefarm: {
    name: "Stone Farm",
    category: "Farms",
    price: { wood: 10, stone: 30 },
    description: "+5 stone per second",
    rate: { stone: 5 },
    model: "stonefarm",
    image: "img/stone.png",
  },
  quarry: {
    name: "Quarry",
    category: "Farms",
    price: { wood: 40, stone: 80 },
    description: "+15 stone per second (requires power)",
    rate: { stone: 15 },
    model: "quarry",
    image: "img/stone.png",
  },
  garden: {
    name: "Garden",
    category: "Farms",
    price: { wood: 20, stone: 5 },
    description: "+2 food per second",
    rate: { food: 2 },
    model: "garden",
    image: "img/dirt.png",
  },
  greenhouse: {
    name: "Greenhouse",
    category: "Farms",
    price: { wood: 80, stone: 40 },
    description: "+10 food per second (requires power)",
    rate: { food: 10 },
    model: "greenhouse",
    image: "img/dirt.png",
  },
  dirtpath: {
    name: "Dirt Path",
    category: "Paths",
    price: { wood: 5, stone: 0 },
    description: "its a dirt path",
    model: "dirtpath",
    image: "img/dirt.png",
  },
  campfire: {
    name: "Campfire",
    category: "Energy",
    price: { wood: 5, stone: 0 },
    description: "its a campfire",
    radius: 5,
    model: "campfire",
    image: "img/dirt.png",
  },
  windturbine: {
    name: "Wind Turbine",
    category: "Energy",
    price: { wood: 25, stone: 40 },
    description: "Provides power to nearby farms (radius 6)",
    radius: 6,
    model: "windturbine",
    image: "img/dirt.png",
  },
  solarpanel: {
    name: "Solar Panel",
    category: "Energy",
    price: { wood: 40, stone: 10 },
    description: "Provides power to nearby farms (radius 4)",
    radius: 4,
    model: "solarpanel",
    image: "img/dirt.png",
  },
  generator: {
    name: "Generator",
    category: "Energy",
    price: { wood: 60, stone: 80 },
    description: "Powered generator; provides strong power (radius 8)",
    radius: 8,
    model: "generator",
    image: "img/dirt.png",
  },
  tent: {
    name: "Tent",
    category: "Housing",
    price: { wood: 20, stone: 5 },
    description: "Basic shelter for a settler",
    model: "tent",
    image: "img/dirt.png",
  },
  cabin: {
    name: "Cabin",
    category: "Housing",
    price: { wood: 100, stone: 50 },
    description: "A comfortable cabin",
    model: "cabin",
    image: "img/dirt.png",
  },
};
